name: tg_utils
description: Collection of utils to simplify Telegram integration
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.1

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  synchronized: ^3.1.0+1
  teledart:
    git:
      url: https://github.com/GoodVibesDev/TeleDart.git

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
